### ISSUE TITLE
Comparison with Restic

### ISSUE THREAD

**Issue by ThatIsAPseudo** [josephernest/nfreezer#5]
Could you add a comparison with [restic](https://github.com/restic/restic) to the table in the readme ?
Thanks for your work !

**Comment by josephernest** [comment]
Good idea @ThatIsAPseudo, thanks for sharing it!

I added it to the list of other backup tools to test, I'll do it when I have time. (It always takes time because each new tool has many options, etc. and some details are important, for example - for those I have tested - the file-renaming questions, etc.). See also https://github.com/josephernest/nfreezer/issues/6.

The best place to do a more detailed comparison with other tools would probably be a blog post, rather than this repo, I'll think about this!
